#!/bin/sh

### BEGIN INIT INFO
# Provides:          box_display
# Required-Start:
# Required-Stop:     box_display
# Should-Stop:       
# X-Start-Before:    box_display
# Default-Start:     S
# Default-Stop:      0 1 6
# Short-Description:
# Description:       
### END INIT INFO

set -e

# Include core init functions if needed
#. /lib/lsb/init-functions

case "${1:-}" in
  stop|reload|restart|force-reload)
        echo "Stopping main PD patch..."
	kill `cat /var/run/pd_main_patch.pid`
        ;;

  start)
        echo "Starting main PD patch... "
	cd /home/pi/PiOSCBox/lib/pd
        pd -nogui /home/pi/PiOSCBox/lib/pd/main.pd 2>&1 >> /dev/null &
	echo $! > /var/run/pd_main_patch.pid 
	;;

  *)
        echo "Usage: ${0:-} {start|stop|status|restart|reload|force-reload}" >&2
        exit 1
        ;;
esac
