#!/bin/sh

### BEGIN INIT INFO
# Provides:          box_display
# Required-Start:
# Required-Stop:     box_display
# Should-Stop:       
# X-Start-Before:    box_display
# Default-Start:     S
# Default-Stop:      0 1 6
# Short-Description:
# Description:       
### END INIT INFO

set -e

# Include core init functions if needed
#. /lib/lsb/init-functions

case "${1:-}" in
  stop|reload|restart|force-reload)
        echo "Stopping box_display."
	kill `cat /var/run/box_display.pid`
        ;;

  start)
        echo "Starting box_display... "
	cd /home/pi/PiOSCBox/bin
        /home/pi/PiOSCBox/bin/display &
	echo $! > /var/run/box_display.pid 
	sleep 1
	;;

  *)
        echo "Usage: ${0:-} {start|stop|status|restart|reload|force-reload}" >&2
        exit 1
        ;;
esac
